api:
  name: "is-flights-pa"
  basepath: "is-flights-pa/api/${api.version}"
  version: "v1"
  
system-api:
  host: "localhost"
  port: "8089"
  basepath: "is-flights-sa/api/${system-api.version}"
  version: "v1"
  timeout: "180000" 
  
mq:
  host: "localhost"
  port: "5672"
  username: "guest"
  password: "guest"
  
dir:
  parkingLot: 'C:\Users\ishulia\AnypointStudio\workspace02'
