#%RAML 1.0
title: Flights Process API
version: v1

types:
  Flight: !include datatypes/Flight.raml

/flights:
  get:
    queryParameters:
      destination?:
        type: string
        enum: ["SFO", "LAX", "CLE"]
        displayName: Flight Destination
        description: IATA code of the airport where the flight is scheduled to arrive.
        example: "LAX"

    responses:
      200:
        body:
          application/json:
            type: Flight[]
            example: !include examples/flights-example.json

  /{flightId}:
    get:
      responses:
        200:
          body:
            application/json:
              type: Flight
              example: !include examples/flight-example.json

/countries:
  /triggerScheduler:
    post:
      description: Trigger scheduler that publishes events
      responses:
        202:
          description: Process started.

/weatherSnapshot:
  get:
    description: Retreive weather information for country capital
    queryParameters:
      countryCode:
        description: Code of the country to get capital weather for
        required: true
        type: string
        example: "UA"
    responses:
      200:
        body:
          application/json:
            example: !include examples/weather-db-example.json